name: System Tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main, master]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to run tests on (leave empty for all platforms)'
        required: false
        type: choice
        options:
          - ''
          - windows-latest
          - ubuntu-latest
          - macos-latest
        default: ''
jobs:
  system-tests-on-all-platforms:
    if: github.event_name != 'workflow_dispatch' || github.event.inputs.platform == ''
    name: Run System Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
      max-parallel: 1
    steps:
      - name: Check prerequisites
        uses: ./.github/workflows/sys_tests_steps/check_prerequisites.yml

      - name: Run system tests
        uses: ./.github/workflows/sys_tests_steps/run_sys_tests.yml

  system-tests-on-specific-platform:
    if: github.event_name == 'workflow_dispatch' || github.event.inputs.platform != ''
    name: Run System Tests
    runs-on: ${{ github.event.inputs.platform }}
    steps:
      - name: Check prerequisites
        uses: ./.github/workflows/sys_tests_steps/check_prerequisites.yml

      - name: Run system tests
        uses: ./.github/workflows/sys_tests_steps/run_sys_tests.yml
