name: System Tests

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
    branches: [main, master]
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to run tests on'
        required: true
        type: choice
        options:
          - all
          - windows-latest
          - ubuntu-latest
          - macos-latest
        default: all
jobs:
  system-tests:
    name: Run System Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.platform != 'all' && fromJSON(format('["{0}"]', github.event.inputs.platform)) || fromJSON('["windows-latest", "ubuntu-latest", "macos-latest"]') }}
      max-parallel: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.2'
          check-latest: false

      - name: Install dependencies
        run: go mod download

      # ───────────────────────────────────────── Windows only ─────────────────────────────────────────
      - name: Install git on Windows
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
            choco upgrade chocolatey -y
            choco install git -y --ignore-dependencies
          }

      # ───────────────────────────────────────── Linux only ───────────────────────────────────────────
      - name: Install clipboard utility on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y xclip

      # ───────────────────────────────────────── macOS only ────────────────────────────────────────────
      - name: Install required tools on macOS
        if: runner.os == 'macOS'
        run: |
          # Install gawk (GNU awk) which is required by qs
          brew install gawk
          # Install jq if not already available
          brew install jq

      - name: Configure git identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Install GitHub CLI (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          choco install gh

      - name: Run system tests
        env:
          UPSTREAM_GH_TOKEN: ${{ secrets.UPSTREAM_GH_TOKEN }}
          FORK_GH_TOKEN: ${{ secrets.FORK_GH_TOKEN }}
          UPSTREAM_GH_ACCOUNT: ${{ secrets.UPSTREAM_GH_ACCOUNT }}
          FORK_GH_ACCOUNT: ${{ secrets.FORK_GH_ACCOUNT }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_TICKET_URL: ${{ secrets.JIRA_TICKET_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          GH_TIMEOUT_MS: ${{ vars.GH_TIMEOUT_MS }}
          QS_RETRY_DELAY_SECONDS: ${{ vars.QS_RETRY_DELAY_SECONDS }}
          QS_MAX_RETRY_DELAY_SECONDS: ${{ vars.QS_MAX_RETRY_DELAY_SECONDS }}
          QS_MAX_RETRIES: ${{ vars.QS_MAX_RETRIES }}
          QS_SKIP_QS_VERSION_CHECK: "true"
        run: go test -timeout 20m -v sys_test.go
